/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        /* ── Material Design 3 Semantic Palette ── */
        'primary':                    '#4A5D23',
        'primary-dim':                '#46591f',
        'primary-container':          '#d4eca2',
        'primary-fixed':              '#d4eca2',
        'primary-fixed-dim':          '#c6dd95',
        'on-primary':                 '#edffc4',
        'on-primary-container':       '#45581f',
        'on-primary-fixed':           '#33450d',
        'on-primary-fixed-variant':   '#4f6227',
        'inverse-primary':            '#dff7ac',

        'secondary':                  '#81552c',
        'secondary-dim':              '#734a22',
        'secondary-container':        '#ffdcc1',
        'secondary-fixed':            '#ffdcc1',
        'secondary-fixed-dim':        '#ffca9d',
        'on-secondary':               '#fff7f4',
        'on-secondary-container':     '#724820',
        'on-secondary-fixed':         '#5c3610',
        'on-secondary-fixed-variant': '#7d5229',

        'tertiary':                   '#52616a',
        'tertiary-dim':               '#46555e',
        'tertiary-container':         '#e0f0fb',
        'tertiary-fixed':             '#e0f0fb',
        'tertiary-fixed-dim':         '#d2e2ec',
        'on-tertiary':                '#f3faff',
        'on-tertiary-container':      '#4b5b63',
        'on-tertiary-fixed':          '#394851',
        'on-tertiary-fixed-variant':  '#55656d',

        'error':                      '#9e422c',
        'error-dim':                  '#5c1202',
        'error-container':            '#fe8b70',
        'on-error':                   '#fff7f6',
        'on-error-container':         '#742410',

        'background':                 '#fff9ed',
        'on-background':              '#3b3205',
        'surface':                    '#fff9ed',
        'surface-dim':                '#f2e9c7',
        'surface-bright':             '#fff9ed',
        'surface-tint':               '#52652a',
        'surface-variant':            '#f4ebd0',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#faf4e0',
        'surface-container':          '#faeec1',
        'surface-container-high':     '#f5eed3',
        'surface-container-highest':  '#f2e3a5',
        'on-surface':                 '#3b3205',
        'on-surface-variant':         '#6a5f2e',
        'inverse-surface':            '#110e02',
        'inverse-on-surface':         '#a49d85',

        'outline':                    '#867b47',
        'outline-variant':            '#c0b279',

        /* ── Legacy aliases (keep existing components working) ── */
        trail: {
          tan:       '#c0b279',
          brown:     '#81552c',
          darkBrown: '#5c3610',
          blue:      '#52616a',
          darkBlue:  '#46555e',
          green:     '#4A5D23',
          red:       '#9e422c',
          gold:      '#c0b279',
          cream:     '#fff9ed',
          parchment: '#f5eed3',
        },
        game: {
          parchment: '#faf4e0',
          parchDark: '#f5eed3',
          amber:     '#81552c',
          amberDk:   '#5c3610',
          green:     '#4A5D23',
          red:       '#9e422c',
          blue:      '#52616a',
          gold:      '#c0b279',
          ink:       '#3b3205',
          inkLt:     '#6a5f2e',
        },
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body:     ['"Noto Serif"', 'serif'],
        label:    ['"Work Sans"', 'sans-serif'],
        /* Legacy aliases */
        display:  ['Newsreader', 'serif'],
        serif:    ['"Noto Serif"', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg:      '0px',
        xl:      '0px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
